name: daravel_core
description: 'A new Flutter package project.'
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.2

dependencies:
  analyzer: ^6.8.0
  args: ^2.5.0
  dotenv: ^4.2.0
  shelf: ^1.4.1
  shelf_router: ^1.1.0
  path: ^1.9.0

dev_dependencies:
  http: ^1.2.2
  lints: ^4.0.0
  test: ^1.25.7

executables:
  dartisan:
